version: "3.8"

services:
  dev_database:
    container_name: diploma_db
    image: postgres:15.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database_dev:/var/lib/postgresql/data
    ports:
      - "54324:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -h localhost -d ${DB_NAME}"]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 3
    command: ["docker-entrypoint.sh", "postgres"]

volumes:
  database_dev:
